apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth

spec:
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      restartPolicy: Always
      containers:
        - name: redis-auth
          image: redis:7
          args: ["--requirepass", "$(REDIS_AUTH_PASSWORD)"]
          envFrom:
            - secretRef:
                name: users-configmap
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-auth
spec:
  selector:
    app: redis-auth
  ports:
    - port: 6379
      targetPort: 6379
