networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure
    driver: bridge

services:
  gateway:
    container_name: ${GATEWAY_SERVICE_HOST}
    build:
      context: ../../production
      dockerfile: ../deploy/docker/Dockerfile
      args:
        SERVICE_NAME: gateway
    env_file:
      - ../../config/.env.test
    restart: always
    hostname: ${GATEWAY_SERVICE_HOST}
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
    depends_on:
      - users

  users:
    container_name: ${USERS_SERVICE_HOST}
    build:
      context: ../../production
      dockerfile: ../deploy/docker/Dockerfile
      args:
        SERVICE_NAME: users
    env_file:
      - ../../config/.env.test
    restart: always
    hostname: ${USERS_SERVICE_HOST}
    networks:
      - backend
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}"
    depends_on:
      - users_db
  users_db:
    container_name: "${USERS_POSTGRES_HOST}"
    image: postgres:16.2-alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=${USERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USERS_POSTGRES_DB}
      - POSTGRES_HOST=${USERS_POSTGRES_HOST}
    ports:
      - "${USERS_POSTGRES_PORT}:5432"
    volumes:
      - db-data-users:/var/lib/postgresql/data
  pepp:
    container_name: pepp
    restart: always
    env_file:
      - ../../config/.env.test
    build:
      context: ../../production
      dockerfile: ../deploy/docker/Dockerfile.client
    ports:
      - "${CLIENT_PORT}:3000"
    networks:
      - frontend
  posts:
    container_name: ${POSTS_SERVICE_HOST}
    build:
      context: ../../production
      dockerfile: ../deploy/docker/Dockerfile
      args:
        SERVICE_NAME: posts
    env_file:
      - ../../config/.env
    restart: always
    hostname: ${POSTS_SERVICE_HOST}
    networks:
      - backend
    ports:
      - "${POSTS_SERVICE_PORT}:${POSTS_SERVICE_PORT}"
    depends_on:
      - posts_db
  posts_db:
    container_name: "${POSTS_POSTGRES_HOST}"
    image: postgres:16.2-alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTS_POSTGRES_DB}
      - POSTGRES_HOST=${POSTS_POSTGRES_HOST}
    ports:
      - "${POSTS_POSTGRES_PORT}:5432"
    volumes:
      - db-data-posts:/var/lib/postgresql/data

volumes:
  db-data-users:
  db-data-posts:

    # links:
    #  - db

  # Uncomment to enable MongoDB
  # db:
  #   image: "mongo"
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  #     MONGO_USER: ${MONGO_USER}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #     TZ: "Europe/Warsaw"
  #   volumes:
  #     - "./db/data/db-files:/data/db"
  #     - "./db/init/:/docker-entrypoint-initdb.d/"
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - backend

  # Uncomment to enable redis
  # redis:
  #   image: redis
  #   restart: always
  #   hostname: redis
  #   networks:
  #     - backend
  #   env_file:
  #     - ../../config/.env

  # Uncomment to enable RabbitMQ
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   restart: always
  #   hostname: rabbitmq
  #   networks:
  #     - frontend
  #     - backend
  #   env_file:
  #     - ../../config/.env
  #   # Uncomment to initialize RabbitMQ with predefined configuration
  #   # volumes:
  #   #  - './configs/rabbitmq-init.json:/tmp/rabbitmq-init.json'
  #   # environment:
  #   #  - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbitmq-init.json"

  #   # Uncomment to expose RabbitMQ Management service port
  #   # ports:
  #   #  - "15672:15672"
