---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-configmap
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgCkuyRZ0g8NMS4hcX+nE5bjJZ8WSKhNjbqn/SluHk1gtoN2efh1xyLJ5+QT3WQct4e3+24TkBvQggTYFC3r0pVWWY9X6S8KYZ6nHCw/qfgUQfHbh8jpFkCnDlq/U3XTGnBU55pj8DNBNXHvtfMgHoQ2dz1JxL1ojoiC8tPOYEGIjkVQDXebuCWy8eFHTLQX9E54p4Jh/7IeuD5G6MsF45hhFAvyKj5B+2t9cTJKZYOOXuTfv/4CVNMSPPulZVlfQcSh+B05Osr8vNRLSWHqZoQfYv5iBslhHgcF9RRSniMsOEqLXomaseAT5UMQrl4wfdGBLTQHjwMmeWRTDP2QYl1sMkDzP90PGGWbRDbwUNU84RNDAHnJjS2BjFTz44oIbS1hJ7JH2JrWJgGkh4DCvyqDbMuW5slCmS9zp/YDnmWIt0SZwfd+ijCc/SEUEZw2yURfe84a1F+7cEaeNsF9l1lykR6g9MmEQXd/SlHWL23bgJTa6Y8yoX4lg4WHq8qx02ofzcq0MQMjf1rFgQZjHNl86uB19BdrwaRLzhm1jgwhbsl5/wwfv17q9Ft8Qi60uaBO76PuEX0SGAsEX7bRl5DIHtkH8pR2a4eHHLdmEu027LwPp7O0kntvyouarU8H1E5Lbe0a5QuejbOsWHXM6nvmXkkbkCDXmkvTcEqyj0M5t0xhUhyqqkOwIaLY0K9uLgoxH4lRzjKCV0yXBA0Z206JYfWSgoEpPjk=
    REDIS_AUTH_PASSWORD: AgAFxVh1z54KjBVnZof5QJU82uvxA1phVLPI2b/QXhJimpC0/FAEfg7xNpAbHMbntAHRKmEUP339qgkccV5dOK35ImShlSVy9A4V4zLjaYC9FAQXz5uqsAfrqIitkUFtF0c5+8U09Y27/sWTmWtz980/spRPr8A1uT6Jzidd03rdHKzqxSum7PsCUbzVlP/dHDyqZrihOkxQnzAC73RTaCeP9GfQWbdNRVX+nPlzmp1zfS3jaiKfbM6LRn/RaIHNLQCS+kB0Vi3ep8VohfpGcZn8hhMUq9C3Jc3/W7CrfNOTAQC/xhzf8ylZ+VdPq0pQOF3raP4sH5f9zzYH+eEVlC5frJ1dFrhKkIMwssNdeRli8UjUUXeqFgo+dOSkndX2VLVruFGEV6ELJy8tkD7muXWElDRyCUEwFqtIKYstbTl1eTyEkeqFC4KO9hzJ/sm28NVaIKGRSB+HSI1NCKbr6ZKDGIe83Q+0EZtGz2bGqORjuL2JjPb0XE243tt+kMgQvEmXfbI4kPmt3oTN8TxQPUqnzEPEeKid7M6iykAJYXJJrgdSwVWU0CLnF/PpNWvclW28tEZvPMoJeknX7W8qBba+3Lnm18awPSvQ8PRgTjcNtEKk7xHjP/F1H1BZ7IicNusZSnaZ/rfqikQ1uT18M9j3Im4Ije3SFXHPCItDGQYKa967L56dn4d+5fBckP7gHofpsW7An5GwFpqQ86PrMwZJJB/kjWJmUpJUu21OXQ==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-configmap
      namespace: default
