---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: server-secret
  namespace: default
spec:
  encryptedData:
    NEXTJS_ENDPOINTS_TOKEN: AgBMWCo1QTHS/0OioR5RfP8by50AxWgBD87UBM2rrK0/G0ONeEAJadqTQNww55TssnbTylSyEZQolPjqGY0XF4DMkANiTQCI4C/xGuhaylFCyH/Ko0ZGkhKigMDqUYvSW+YC0Yu5LwYc1dRBbxL9/Je2FjbFE9FH6Eo/DvcXfG0o8hS0SuC3eXbGjsXheKzU+TV8e7sx29J1y1o7ZUoAUWkK9zABrp/x7oHwCpbqY4hCQyKSySP8YxkKma95o0CBteOdRL3TgxoYCxAexNfJaxh0MrHMSXL6KWym7cwVpGa15ZrsWH3CyPJa5eESKSHuWYcMSQGS+5Q4Aj3x0y5ox9j8Kpq2lU9q0+q09GyAVg/9vKJjBALp2mXqleWC+pSqzSWoGIKFKdpNQdgY1iA7bgffxjsPX+h64kqfu57rGizhGkiPh+592q577w06ApEvDJzh8XoveNP4SW6Q5d/PRlRnsPfmZkNeDd0wwceERKLZkeSmW0TDWgRWoSDI3Gq2124vAiXRVAiouEQ36yybA3HAqykSwJ+MePpj2R13FozYa7qfhkt8nVoJQluxo6kPekBsNNguXopHfNxCbsdnX4JoU11rOR+UycWnpK+yHDIQQST0bT7d1BltVqsP+2qSxKEiNoRVihypy8KaUn4rLoHowm+iAHDcytUixASMfGxV+SJHFyKMMuLwkfL+ZdM7t7mdmsAomR54MVVp0uvF3/o=
  template:
    metadata:
      creationTimestamp: null
      name: server-secret
      namespace: default
