apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: "genorred/client-pepp:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: global-configmap
      #     readinessProbe:
      #       tcpSocket:
      #         port: 8080
      #       initialDelaySeconds: 5
      #       periodSeconds: 5
      #     livenessProbe:
      #       httpGet:
      #         path: /status
      #         port: 8080
      # imagePullSecrets:
      #   - name: dpr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000
