apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: "genorred/posts-pepp:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: global-configmap
            - secretRef:
                name: server-secret
            - secretRef:
                name: posts-secret
      #     readinessProbe:
      #       tcpSocket:
      #         port: 8080
      #       initialDelaySeconds: 5
      #       periodSeconds: 5
      #     livenessProbe:
      #       httpGet:
      #         path: /health
      #         port: 8080
      # imagePullSecrets:
      #   - name: dpr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
    - port: 8080
      targetPort: 8080
