FROM cypress/included:13.7.3

WORKDIR /usr
COPY . .

ENV PATH="$PNPM_HOME:$PATH"

RUN npm i -g pnpm

COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install --frozen-lockfile
COPY . .

CMD ["pnpm", "run", "cypress"]
