FROM node:20.16.0-alpine

WORKDIR /usr/app


RUN npm i -g pnpm

WORKDIR /usr/app/client
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install --frozen-lockfile

COPY . .

VOLUME [ "/usr/app/client/node_modules", "/usr/app/client/.next" ]

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
