import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/widgets/Navbar";
import { Providers } from "@/widgets/Providers";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/shared/lib/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <Providers>
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <main >
          <Navbar />
          <div className='font-bold'>
            {children}
          </div>
        </main>
        </body>

      </Providers>
      </html>
    );
}