import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/widgets/Navbar";
import { Providers, roboto } from "@/widgets/Providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <Providers>
        <body className={roboto.variable}>
        <main >
          <Navbar />
          <div className='font-bold'>
            {children}
          </div>
        </main>
        </body>

      </Providers>
      </html>
    );
}